name: Quarkup Assort

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  Assort:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: 'Git: checkout'
        uses: actions/checkout@v4

      - name: 'Python: setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Python: install packages'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Python: execute'
        env:
          AQ: ${{ secrets.AQ }}
        # run: python scripts/assort.py
        run: python source/test.py

      # - name: Git.commit
      #   run: |
      #     git config --local user.email "sup2point0@gmail.com"
      #     git config --local user.name "GitHub Actions"
      #     git add -A
      #     git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      # - name: Git.push
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.STIG }}
      #     branch: origin
