name: Quarkup Assort

on:
  workflow_dispatch:
  
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  Assort:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: 'Git: checkout'
        uses: actions/checkout@v4

      - name: 'Python: setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 'Python: install packages'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Python: execute'
        env:
          AQ: ${{ secrets.CHARM }}
        # run: python scripts/assort.py
        run: python source/test.py
