name: Tests

on:
  workflow_dispatch:

  schedule:
    - cron: '20 4 * * 2,6'
  
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Git – checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: 'Python – setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 'Python – install'
        run: |
          python -m pip install --upgrade pip
          # pip install flake8 pytest
          pip install -r requirements.txt
          
      - name: 'Pytest – execute'
        run: pytest -vv
