name: Tests

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Git: checkout'
        uses: actions/checkout@v3
      
      - name: 'Python: setup'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: 'Python: installs'
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
          
      - name: 'Python: execute'
        run: |
          pytest tests/quarkify.py
